src/main/java/org/example/tablenow/domain/category/controller/CategoryController.java
src/main/java/org/example/tablenow/domain/category/repository/CategoryRepository.java
src/main/java/org/example/tablenow/domain/category/service/CategoryService.java
src/main/java/org/example/tablenow/domain/store/dto/response/StoreSearchResponseDto.java
src/main/java/org/example/tablenow/domain/store/repository/StoreQueryRepository.java
src/main/java/org/example/tablenow/domain/store/repository/StoreQueryRepositoryImpl.java
src/main/java/org/example/tablenow/domain/store/service/StoreService.java
src/main/java/org/example/tablenow/domain/store/util/StoreUtils.java
src/main/java/org/example/tablenow/global/exception/ErrorCode.java

close #13
- StoreService 의 `validStoreOwnerId` -> public 변경

[fix] 가게, 카테고리 수정

---

src/main/java/org/example/tablenow/domain/auth/controller/AuthController.java
src/main/java/org/example/tablenow/domain/auth/service/AuthService.java
src/main/java/org/example/tablenow/domain/auth/service/TokenService.java
src/main/java/org/example/tablenow/domain/user/enums/UserRole.java
src/main/java/org/example/tablenow/global/exception/ErrorCode.java

[refactor] 인증/인가 예외 처리 개선

---

src/main/java/org/example/tablenow/domain/store/controller/StoreController.java
src/main/java/org/example/tablenow/domain/store/entity/Store.java
src/main/java/org/example/tablenow/domain/store/service/StoreService.java
src/main/java/org/example/tablenow/domain/store/util/StoreUtils.java

[refactor] 가게 기능 개선

---

src/main/java/org/example/tablenow/domain/reservation/controller/ReservationController.java
src/main/java/org/example/tablenow/domain/reservation/service/ReservationService.java
src/main/java/org/example/tablenow/global/exception/ErrorCode.java

[refactor] 예약 API 피드백 반영 수정

---

src/main/java/org/example/tablenow/domain/auth/entity/RefreshToken.java
src/main/java/org/example/tablenow/domain/auth/service/AuthService.java
src/main/resources/application-test.yml
src/test/java/org/example/tablenow/domain/auth/service/AuthServiceTest.java
src/test/java/org/example/tablenow/domain/auth/service/TokenServiceTest.java

close #10
- application-test.yml 생성하여 테스트 환경 분리
- `@Activeprofiles("test")` 어노테이션 적용으로 테스트 설정 분리

[test] 인증/인가 테스트 코드 작성

---

src/main/java/org/example/tablenow/global/util/JwtUtil.java

close #31
- [트러블슈팅](https://www.notion.so/teamsparta/1cf2dc3ef514801389a6d85aa0b998ca)

[fix] Access Token 고유성 보장 로직 수정

---

.gitignore
src/main/resources/application-local.yml
src/main/resources/application-test.yml
src/main/resources/application.yml

close #23
프로필별 jpa hibernate ddl 전략 변경 필요
각자 개발환경에 맞게 .env.local / .env.test 파일 작성하시면 됩니다. (스크린샷 참고)
local: 로컬 MySql, test: Docker MySql 이라고 가정
* `.env`
* `.env.local`
* `.env.test`

[chore] 프로필별 설정 변경

---

src/main/java/org/example/tablenow/global/exception/ErrorCode.java

close #42 
pull 받은 후 ErrorCode 컴파일 에러 확인 후 수정합니다.

[fix] 에러코드 중복 수정

---

src/main/java/org/example/tablenow/domain/event/dto/request/EventRequestDto.java
src/main/java/org/example/tablenow/domain/event/dto/request/EventUpdateRequestDto.java
src/main/java/org/example/tablenow/domain/event/service/EventService.java
src/test/java/org/example/tablenow/domain/event/EventJoinServiceTest.java
src/test/java/org/example/tablenow/domain/event/EventServiceTest.java

[test] 이벤트 API 테스트코드 작성

---

src/main/java/org/example/tablenow/domain/notification/controller/NotificationController.java
src/main/java/org/example/tablenow/domain/notification/repository/NotificationRepository.java
src/main/java/org/example/tablenow/domain/notification/service/NotificationService.java
src/test/java/org/example/tablenow/domain/notification/service/NotificationServiceTest.java

feat: 알림 조회 페이지네이션 및 필터링 기능 추가

---

src/main/java/org/example/tablenow/domain/store/controller/StoreController.java
src/main/java/org/example/tablenow/domain/store/dto/request/StoreCreateRequestDto.java
src/main/java/org/example/tablenow/domain/store/dto/request/StoreUpdateRequestDto.java
src/main/java/org/example/tablenow/domain/store/service/StoreService.java
src/main/java/org/example/tablenow/domain/store/util/StoreRedisKey.java
src/main/java/org/example/tablenow/global/exception/ErrorCode.java
src/test/java/org/example/tablenow/domain/store/service/StoreServiceTest.java

close #50
close #48
*  `/api/v1/stores`: 사용자 기준 검색어 조회 수 어뷰징 방지
* `/api/v1/stores/ranking` 시간별, 일자별 인기 검색어 저장 및 조회
* `/api/v1/stores/ranking` 인기 검색 랭킹 조회
> `@RequestParam(defaultValue = "10")` int limit 
> limit 개 까지의 랭킹 조회
> `@RequestParam(required = false)` String timeKey 
> yyyyMMddHH: 시간별, yyyyMMdd: 일자별 / 미입력시 현재 시간 기준으로 조회
* 2025-04-09 21시 랭킹 조회
* 2025-04-09 22시 랭킹 조회
* 2025-04-09 랭킹 조회

[refactor] 가게 기본 기능 개선

---

src/main/java/org/example/tablenow/domain/image/annotation/ImageUrlPattern.java
src/main/java/org/example/tablenow/domain/image/annotation/ImageUrlValidator.java
src/main/java/org/example/tablenow/domain/image/service/ImageService.java
src/main/java/org/example/tablenow/domain/store/annotation/HalfHourOnly.java
src/main/java/org/example/tablenow/domain/store/annotation/HalfHourValidator.java
src/main/java/org/example/tablenow/domain/store/dto/request/StoreCreateRequestDto.java
src/main/java/org/example/tablenow/domain/store/dto/request/StoreUpdateRequestDto.java
src/main/java/org/example/tablenow/domain/store/service/StoreService.java
src/main/java/org/example/tablenow/global/config/S3Config.java
src/main/java/org/example/tablenow/global/exception/ErrorCode.java
src/main/java/org/example/tablenow/global/exception/GlobalExceptionHandler.java

close #67
#68
#67
> 요청 데이터의 validation 에러 메세지를 처리하는 MethodArgumentNotValidException Handler 추가
#68
> 가게 수정, 삭제 시 기존 이미지가 있는 경우 해당 이미지 리소스 찾아서 삭제
* #67 (복수 예외메세지 처리)
* #68 가게 수정 - 이미지 등록
* `@ImageUrlPattern` -> 입력한 이미지 주소가 null 또는 URL 형식인지 검증

[refactor] 가게 이미지 리소스 처리

---

src/main/java/org/example/tablenow/domain/auth/service/AuthService.java
src/main/java/org/example/tablenow/domain/user/service/UserService.java

close #82 
- 유저 조회하실 때 아래 메서드 사용하시면 됩니다!
- ID 기준 조회 메서드: getUser
- 이메일 기준 조회 메서드: getUserByEmail

[refactor]: 유저 조회 메서드 공통화

---

src/main/java/org/example/tablenow/domain/user/dto/request/UpdatePasswordRequest.java
src/main/java/org/example/tablenow/domain/user/dto/request/UpdateProfileRequest.java
src/main/java/org/example/tablenow/domain/user/dto/request/UserDeleteRequest.java
src/test/java/org/example/tablenow/domain/user/service/UserServiceTest.java

close #71 
- `@Builder`를 request DTO 클래스 선언부에 추가했습니다.

[test] UserService 단위 테스트 작성

---

src/main/java/org/example/tablenow/domain/event/dto/response/EventDeleteResponseDto.java
src/main/java/org/example/tablenow/domain/event/dto/response/EventJoinResponseDto.java
src/main/java/org/example/tablenow/domain/event/dto/response/EventResponseDto.java
src/main/java/org/example/tablenow/domain/event/entity/Event.java
src/main/java/org/example/tablenow/domain/event/repository/EventJoinRepository.java
src/main/java/org/example/tablenow/domain/event/service/EventJoinService.java
src/main/java/org/example/tablenow/domain/event/service/EventOpenScheduler.java
src/main/java/org/example/tablenow/domain/event/service/EventService.java

close #78 
- 알림 생성 → MQ에 메세지 발행으로 고도화 예정
- [의존성 순환(circular dependency) 에러 트러블슈팅](https://www.notion.so/teamsparta/circular-dependency-1d22dc3ef514804590c2fdfca661dd13?pvs=4)

[refactor] 이벤트 API 피드백 반영 리팩토링

---

src/main/java/org/example/tablenow/domain/reservation/service/ReservationService.java
src/main/java/org/example/tablenow/domain/store/service/StoreService.java
src/test/java/org/example/tablenow/domain/reservation/ReservationServiceTest.java

close #93 
* 해당 가게의 주인 유저인지 확인하는 validStoreOwnerId() 의 메서드명을 validateStoreOwnerId() 로 변경
* 미사용 메서드 getStoreTimeSlots() 삭제
메서드명 변경으로 기존 validStoreOwnerId()를 호출하는 
ReservationService, ReservationServiceTest 에 코드 변경이 있습니다.

[refactor] 가게 메서드명 변경 및 미사용 메서드 삭제

---

src/test/java/org/example/tablenow/domain/auth/service/KakaoAuthServiceTest.java
src/test/java/org/example/tablenow/domain/auth/service/NaverAuthServiceTest.java
src/test/java/org/example/tablenow/testutil/OAuthTestUtil.java

close #70 
- `mockWebClientTokenRequest()` 메서드는 Mockito의 `PotentialStubbingProblem` 예외가 발생하여 공통화 대상에서 제외했습니다.

[test] 소셜 로그인 테스트 코드 작성

---

src/main/java/org/example/tablenow/domain/image/dto/request/PresignedUrlRequest.java
src/main/java/org/example/tablenow/domain/image/service/ImageService.java
src/test/java/org/example/tablenow/domain/image/service/ImageServiceTest.java

close #96 
- `ImageService`에서 private 메서드를 클래스 하단으로 이동하여 구조 정리

[test] 이미지 서비스 테스트 코드 작성

---

src/main/java/org/example/tablenow/domain/rating/controller/RatingController.java
src/main/java/org/example/tablenow/domain/rating/dto/request/RatingRequestDto.java
src/main/java/org/example/tablenow/domain/rating/dto/response/RatingCreateResponseDto.java
src/main/java/org/example/tablenow/domain/rating/dto/response/RatingDeleteResponseDto.java
src/main/java/org/example/tablenow/domain/rating/dto/response/RatingUpdateResponseDto.java
src/main/java/org/example/tablenow/domain/rating/entity/Rating.java
src/main/java/org/example/tablenow/domain/rating/repository/RatingRepository.java
src/main/java/org/example/tablenow/domain/rating/service/RatingService.java
src/main/java/org/example/tablenow/domain/reservation/repository/ReservationRepository.java
src/main/java/org/example/tablenow/domain/reservation/service/ReservationService.java
src/main/java/org/example/tablenow/domain/store/entity/Store.java
src/main/java/org/example/tablenow/global/exception/ErrorCode.java

close #102
평점 기능 추가로 수정사항이 발생하여 전달드립니다.
예약: `ReservationService`, `ReservationRepository` 
가게: `Store` 
기존 코드에 메서드 추가 등 수정사항이 있습니다. 참고 부탁드립니다. 
- 평점 등록
- 평점 수정
- 평점 삭제

[feat] 평점 API 구현

---

build.gradle
src/main/java/org/example/tablenow/domain/notification/enums/NotificationType.java
src/main/java/org/example/tablenow/domain/notification/service/NotificationService.java
src/main/java/org/example/tablenow/domain/waitlist/controller/WaitlistController.java
src/main/java/org/example/tablenow/domain/waitlist/entity/Waitlist.java
src/main/java/org/example/tablenow/domain/waitlist/service/WaitlistService.java
src/main/java/org/example/tablenow/global/config/RedissonConfig.java
src/main/java/org/example/tablenow/global/exception/ErrorCode.java

close #105 -
300명 동시 요청으로 100명 대기 정원 초과 실험

[Feature] 대기등록 분산락 적용

---

src/main/java/org/example/tablenow/domain/rating/dto/request/RatingRequestDto.java
src/main/java/org/example/tablenow/domain/rating/dto/response/RatingCreateResponseDto.java
src/main/java/org/example/tablenow/domain/rating/dto/response/RatingDeleteResponseDto.java
src/main/java/org/example/tablenow/domain/rating/dto/response/RatingUpdateResponseDto.java
src/main/java/org/example/tablenow/domain/rating/entity/Rating.java
src/main/java/org/example/tablenow/domain/rating/service/RatingService.java
src/main/java/org/example/tablenow/domain/store/dto/response/StoreResponseDto.java
src/main/java/org/example/tablenow/domain/store/dto/response/StoreSearchResponseDto.java
src/main/java/org/example/tablenow/domain/store/entity/Store.java
src/main/java/org/example/tablenow/domain/store/enums/StoreSortField.java
src/main/java/org/example/tablenow/domain/store/repository/StoreQueryRepositoryImpl.java
src/test/java/org/example/tablenow/domain/rating/service/RatingServiceTest.java
src/test/java/org/example/tablenow/domain/store/service/StoreServiceTest.java

close #110
- 가게 단일 조회 `GET /api/v1/stores/{id}`
조회 결과 평점 `averageRating` , 평점수 `ratingCount` 추가
- 가게 목록 조회 `GET /api/v1/stores`
정렬 기준 평점 `averageRating` 추가
조회 결과 평점 `averageRating` , 평점수 `ratingCount` 추가
**- 가게 단일 조회**
**- 가게 목록 조회 (평점 높은 순 정렬)**

[feat] 가게 API 평점 조회 추가

---

src/main/java/org/example/tablenow/domain/event/dto/request/EventRequestDto.java
src/main/java/org/example/tablenow/domain/event/dto/response/EventResponseDto.java
src/main/java/org/example/tablenow/domain/event/entity/Event.java
src/main/java/org/example/tablenow/domain/event/service/EventJoinService.java
src/main/java/org/example/tablenow/global/exception/ErrorCode.java

[refactor] Redisson 기반 이벤트 신청 로직 리팩토링

---

src/test/java/org/example/tablenow/domain/store/service/StoreJdbcRepository.java

close #124 
> 테스트코드 빌드 시 오류 확인 
#124
> 이슈 close 후 테스트코드 필드명 변경이 누락되어 추가합니다.
* 가게 단위테스트 Pass 확인

[refactor] 가게 컬럼명 변경 테스트코드 수정

---

src/main/java/org/example/tablenow/domain/payment/repository/PaymentRepository.java
src/main/java/org/example/tablenow/domain/settlement/controller/SettlementController.java
src/main/java/org/example/tablenow/domain/settlement/dto/response/SettlementOperationResponseDto.java
src/main/java/org/example/tablenow/domain/settlement/dto/response/SettlementResponseDto.java
src/main/java/org/example/tablenow/domain/settlement/dto/response/SettlementSummaryPageDto.java
src/main/java/org/example/tablenow/domain/settlement/entity/Settlement.java
src/main/java/org/example/tablenow/domain/settlement/enums/SettlementStatus.java
src/main/java/org/example/tablenow/domain/settlement/repository/SettlementRepository.java
src/main/java/org/example/tablenow/domain/settlement/service/SettlementService.java
src/main/java/org/example/tablenow/global/exception/ErrorCode.java

[feat] 정산 API 구현

---

src/test/java/org/example/tablenow/domain/waitlist/service/WaitlistServiceTest.java

 test(waitlist) 대기등록 분산락 API 테스트 코드 작성 #149

---

.gitignore
Dockerfile.elasticsearch
Dockerfile.kibana
Dockerfile.logstash
build.gradle
docker-compose-v1.yml
src/main/java/org/example/tablenow/domain/store/controller/StoreController.java
src/main/java/org/example/tablenow/domain/store/controller/StoreSearchController.java
src/main/java/org/example/tablenow/domain/store/dto/request/StoreCreateRequestDto.java
src/main/java/org/example/tablenow/domain/store/dto/response/StoreDocumentResponseDto.java
src/main/java/org/example/tablenow/domain/store/entity/StoreDocument.java
src/main/java/org/example/tablenow/domain/store/repository/StoreQueryRepositoryImpl.java
src/main/java/org/example/tablenow/domain/store/repository/StoreRepository.java
src/main/java/org/example/tablenow/domain/store/service/StoreBulkIndexer.java
src/main/java/org/example/tablenow/domain/store/service/StoreSearchQueryBuilder.java
src/main/java/org/example/tablenow/domain/store/service/StoreSearchService.java
src/main/java/org/example/tablenow/domain/store/service/StoreService.java
src/main/java/org/example/tablenow/global/config/CacheConfig.java
src/main/java/org/example/tablenow/global/config/ElasticSearchConfig.java
src/main/java/org/example/tablenow/global/config/SecurityConfig.java
src/main/java/org/example/tablenow/global/dto/PageResponse.java
src/main/java/org/example/tablenow/global/runner/IndexingRunner.java
src/main/resources/application-local.yml
src/main/resources/elastic/store-mapping.json
src/main/resources/elastic/store-setting.json
src/test/java/org/example/tablenow/domain/store/service/StoreServiceTest.java

close #137 
ElasticSearch 기능 개발 환경 구축 및 가게 검색 기능 ES 도입
필수 환경 설정 및 일부 기본 기능 구현 후 PR 
Docker-compose.yml 파일 변경사항이 있습니다.
* 어플리케이션(myapp), DB(mysql) 이미지 제거
* 어플리케이션, DB 추가 버전은 `docker-compose-v1.yml` 로 업로드 되었습니다.
서버 실행을 위해 다음 작업이 필요합니다. 
* [ElasticSearch 환경변수 설정](https://www.notion.so/teamsparta/ElasticSearch-1dc2dc3ef51480969befcd8bba8ac56a)
* [ElasticSearch 기본 개념](https://www.notion.so/teamsparta/Elastic-Search-1db2dc3ef51480c2af74cfbadf3144dc)
* [RDBMS(v1), Redis(v2), ES(v3) 성능 비교 및 개선(작성중)](https://www.notion.so/teamsparta/RDBMS-v1-Redis-v2-ES-v3-1dc2dc3ef5148033ad12da42846afb7d)
* 검색 버전별 성능 그래프

[feat] 가게 검색 ElasticSearch 도입

---

src/main/java/org/example/tablenow/domain/event/message/consumer/EventOpenConsumer.java
src/main/java/org/example/tablenow/domain/event/service/EventJoinExecutor.java

[refactor] 이벤트 알림 타입 수정 및 RedisTemplate 개선

---

src/test/java/org/example/tablenow/domain/event/EventJoinExecutorTest.java
src/test/java/org/example/tablenow/domain/event/EventServiceTest.java

close #179 
- 기존 알림 생성 로직이 EventService → Consumer 구조로 분리되면서, 알림 관련 테스트는 주석 처리 했습니다.
- MQ 발행은 `EventOpenProducer.send()` 호출 여부만 검증합니다.

[test] 이벤트 오픈 처리 및 참가 인원 제한 예외 테스트 추가

---

src/main/java/org/example/tablenow/domain/chat/repository/ChatMessageRepository.java
src/main/java/org/example/tablenow/domain/chat/service/ChatMessageService.java
src/main/java/org/example/tablenow/domain/reservation/entity/Reservation.java

close #188 
- #180 피드백 사항 반영했습니다!
- 성능 테스트는 아직 진행하지 못했습니다. 추후 추가해서 성능 비교 할 예정입니다!
> [읽음 처리 로직 bulk update 적용](https://www.notion.so/teamsparta/bulk-update-1e02dc3ef514800dbef9c7af23feeac0?pvs=4)

[refactor] 읽음 처리 bulk update 적용 및 상태 판단 로직 리팩토링

---

src/main/java/org/example/tablenow/domain/payment/service/PaymentService.java
src/main/java/org/example/tablenow/domain/settlement/batch/job/SettlementCompleteJobConfig.java
src/main/java/org/example/tablenow/domain/settlement/batch/job/SettlementRegisterJobConfig.java
src/main/java/org/example/tablenow/domain/settlement/batch/schedule/SettlementSchedule.java
src/main/java/org/example/tablenow/domain/settlement/entity/Settlement.java
src/main/java/org/example/tablenow/global/config/DataDBConfig.java
src/main/java/org/example/tablenow/global/config/MetaDBConfig.java
src/main/resources/application-local.yml

[refactor] 전반적인 Batch 구조 리팩터링

---

src/main/java/org/example/tablenow/domain/reservation/controller/ReservationController.java
src/main/java/org/example/tablenow/domain/reservation/dto/request/ReservationRequestDto.java
src/main/java/org/example/tablenow/domain/reservation/dto/request/ReservationSearchRequest.java
src/main/java/org/example/tablenow/domain/reservation/dto/request/ReservationStatusChangeRequestDto.java
src/main/java/org/example/tablenow/domain/reservation/dto/request/ReservationUpdateRequestDto.java
src/main/java/org/example/tablenow/domain/reservation/dto/response/ReservationResponseDto.java
src/main/java/org/example/tablenow/domain/reservation/entity/Reservation.java
src/main/java/org/example/tablenow/domain/reservation/message/customer/ReminderRegisterConsumer.java
src/main/java/org/example/tablenow/domain/reservation/message/customer/ReminderSendConsumer.java
src/main/java/org/example/tablenow/domain/reservation/message/dto/ReminderMessage.java
src/main/java/org/example/tablenow/domain/reservation/message/producer/ReminderRegisterProducer.java
src/main/java/org/example/tablenow/domain/reservation/message/producer/ReminderSendProducer.java
src/main/java/org/example/tablenow/domain/reservation/repository/ReservationRepository.java
src/main/java/org/example/tablenow/domain/reservation/service/ReminderScheduler.java
src/main/java/org/example/tablenow/domain/reservation/service/ReservationService.java

close #198 
- [예약 API  피드백](https://www.notion.so/teamsparta/API-1e02dc3ef5148038a862e97f55ecf402?pvs=4)
- ⚠️ 트러블슈팅
- [dataSource or dataSourceClassName or jdbcUrl is required 에러](https://www.notion.so/teamsparta/dataSource-or-dataSourceClassName-or-jdbcUrl-is-required-1e22dc3ef5148019ad86cbc8b6e0331c?pvs=4)
- [Could not resolve attribute 'storeId' of…에러](https://www.notion.so/teamsparta/Could-not-resolve-attribute-storeId-of-1e22dc3ef51480bd9e3fc52f5326d0c0?pvs=4)
- 추가 리팩토링 해야 할 부분은 다음과 같습니다.
- 스케줄러에 `@SchedulerLock` 적용 
- 이벤트 API 전체 리팩토링
- 리팩토링에 따른 테스트코드 수정
- RabbitMQ Exchange 방식 Direct → Fanout으로 수정

[refactor] 예약 API 피드백 반영 리팩토링

---

src/main/java/org/example/tablenow/domain/settlement/batch/schedule/SettlementSchedule.java
src/main/java/org/example/tablenow/domain/settlement/controller/SettlementController.java
src/main/java/org/example/tablenow/domain/settlement/service/SettlementService.java
src/test/java/org/example/tablenow/domain/payment/service/PaymentServiceTest.java
src/test/java/org/example/tablenow/domain/settlement/batch/job/SettlementCompleteJobConfigTest.java
src/test/java/org/example/tablenow/domain/settlement/batch/job/SettlementRegisterJobConfigTest.java
src/test/java/org/example/tablenow/domain/settlement/batch/schedule/SettlementScheduleTest.java
src/test/java/org/example/tablenow/domain/settlement/service/SettlementServiceTest.java

[test] 정산 API 테스트 코드 작성

---

src/main/java/org/example/tablenow/domain/notification/controller/NotificationController.java
src/main/java/org/example/tablenow/domain/notification/dto/request/NotificationAlarmRequestDto.java
src/main/java/org/example/tablenow/domain/notification/dto/request/NotificationRequestDto.java
src/main/java/org/example/tablenow/domain/notification/dto/request/NotificationSearchRequestDto.java
src/main/java/org/example/tablenow/domain/notification/dto/response/NotificationAlarmResponseDto.java
src/main/java/org/example/tablenow/domain/notification/dto/response/NotificationResponseDto.java
src/main/java/org/example/tablenow/domain/notification/message/vacancy/producer/VacancyProducer.java
src/main/java/org/example/tablenow/domain/notification/scheduler/NotificationScheduler.java
src/main/java/org/example/tablenow/domain/waitlist/dto/request/WaitlistRequestDto.java
src/main/java/org/example/tablenow/domain/waitlist/dto/response/WaitlistResponseDto.java
src/test/java/org/example/tablenow/domain/notification/service/NotificationServiceTest.java

[refactor] Notification/Waitlist 리팩토링 및 코드 정리

---

src/main/java/org/example/tablenow/domain/notification/dto/request/NotificationRequestDto.java

[refactor]  NotificationRequestDto에 @Builder 어노테이션 추가

---

src/test/java/org/example/tablenow/domain/notification/service/NotificationServiceTest.java

[refactor] NotificationServiceTest에 NotificationRequestDto에 builder 패턴 수정

---

src/main/java/org/example/tablenow/domain/reservation/message/producer/ReminderRegisterProducer.java
src/main/java/org/example/tablenow/domain/reservation/message/producer/ReminderSendProducer.java
src/main/java/org/example/tablenow/global/config/RabbitConfig.java
src/main/java/org/example/tablenow/global/constant/RabbitConstant.java

[refactor] 예약 리마인드 알림 Exchange 방식 수정

---

Dockerfile.logstash
docker-compose.yml
src/main/java/org/example/tablenow/global/config/DataDBConfig.java
src/main/resources/application-test.yml

close #223
Logstash : Docker Container → SpringBoot : Host 환경
테이블 신규 컬럼명이 camelCase 로 생성되어 under_score 로 생성되도록 네이밍 전략을 수정
- [Logstash 로컬 환경변수 설정](https://www.notion.so/teamsparta/Logstash-1e32dc3ef51480cdbe31f39e116b2ee9)
- dev Pull 이후 테이블 컬럼명 전략이 `camelCase` 로 설정되어 중복 컬럼 생성 확인
hibernate.physical_naming_strategy → `under_score` 전략으로 수정
* Local 환경 Logstash console
`DBConfig 수정`
* AS-IS
* TO-BE

[fix] Logstash 로컬 환경 구성

---

src/test/java/org/example/tablenow/domain/notification/message/vacancy/service/VacancyRetryServiceTest.java
src/test/java/org/example/tablenow/domain/notification/service/NotificationServiceTest.java
src/test/java/org/example/tablenow/domain/waitlist/service/WaitlistServiceTest.java

[refactor] Waitlist, Notification, VacancyRetry 테스트 코드 리팩토링

---

README.md

close #242 
- `dev` 브랜치에 바로 push를 못해서 pr 만들었습니다!

[docs] README 초안 작성

---

src/main/java/org/example/tablenow/domain/reservation/repository/ReservationRepository.java
src/main/java/org/example/tablenow/domain/reservation/service/ReservationService.java
src/test/java/org/example/tablenow/domain/reservation/ReservationServiceTest.java

close #247 
- merge 후 오류가 발생하지 않는지 확인 부탁드립니다.

[fix] 예약 JPA 메서드 네이밍 오류 일괄 수정

---

src/main/java/org/example/tablenow/domain/store/message/consumer/StoreConsumer.java
src/main/java/org/example/tablenow/domain/store/message/producer/StoreProducer.java
src/main/java/org/example/tablenow/global/config/RabbitConfig.java
src/main/java/org/example/tablenow/global/constant/RabbitConstant.java
src/main/java/org/example/tablenow/global/exception/ErrorCode.java
src/test/java/org/example/tablenow/domain/store/message/StoreConsumerTest.java

close #245 
* 가게 데이터 변경 중 오류 발생 시 ES Index, Cache 와 DB 의 데이터 불일치 발생
-> 데이터 정합성 에러 발생 가능성이 높아 RabbitMQ 메시지 처리 에러 시 복구 로직 필요
* DLQ, DLX 를 적용하여 에러 발생 시 3회 재시도
* 네트워크 에러 등 일시적 오류로 인한 실패 시 30초 대기 후 재시도
- DLQ, DLX 빈 등록으로 RabbitConfig 수정하였습니다.
- RabbitMQ 처리 중 예외처리 메시지 추가로 ErrorCode 수정하였습니다.

[feat] 가게 데이터 변경 DLQ + DLX 적용

---

src/test/java/org/example/tablenow/domain/payment/service/PaymentServiceTest.java

[fix] paymentRepository의 연관관계 메서드명 변경으로 인한 test code 수정

---

src/main/java/org/example/tablenow/domain/payment/controller/PaymentController.java

[fix] PaymentController의 cancelPayment @PatchMapping으로 변경

---

build.gradle
src/main/java/org/example/tablenow/domain/auth/controller/AuthController.java
src/main/java/org/example/tablenow/domain/category/controller/CategoryController.java
src/main/java/org/example/tablenow/domain/chat/controller/ChatController.java
src/main/java/org/example/tablenow/domain/chat/controller/ChatMessageController.java
src/main/java/org/example/tablenow/domain/event/controller/EventController.java
src/main/java/org/example/tablenow/domain/event/controller/EventJoinController.java
src/main/java/org/example/tablenow/domain/image/controller/ImageController.java
src/main/java/org/example/tablenow/domain/notification/controller/NotificationController.java
src/main/java/org/example/tablenow/domain/payment/controller/PaymentController.java
src/main/java/org/example/tablenow/domain/payment/controller/PaymentViewController.java
src/main/java/org/example/tablenow/domain/rating/controller/RatingController.java
src/main/java/org/example/tablenow/domain/reservation/controller/ReservationController.java
src/main/java/org/example/tablenow/domain/settlement/controller/SettlementController.java
src/main/java/org/example/tablenow/domain/store/controller/StoreController.java
src/main/java/org/example/tablenow/domain/store/controller/StoreSearchController.java
src/main/java/org/example/tablenow/domain/user/controller/UserController.java
src/main/java/org/example/tablenow/domain/waitlist/controller/WaitlistController.java
src/main/java/org/example/tablenow/global/config/SecurityConfig.java
src/main/java/org/example/tablenow/global/config/SwaggerConfig.java

close #263
혹시 밑에 스크린 샷 보고 각자 맡은 부분에 설명 제대로 적었는지 확인 부탁드려도 될까요
http://localhost:8080/swagger-ui/index.html (스웨거 유아이 접속)

[feat] Swagger 설정 및 전체 API 문서화 적용 

---

src/main/java/org/example/tablenow/global/dummy/DummyDataInitializer.java

[feature]  더미 데이터 초기화 기능 추가
