spring-team-7/table-now

- src/main/java/org/example/tablenow/domain/store/dto/request/StoreCreateRequestDto.java
- src/main/java/org/example/tablenow/domain/store/dto/request/StoreUpdateRequestDto.java
- src/main/java/org/example/tablenow/domain/store/enums/StoreSortField.java
- src/main/java/org/example/tablenow/domain/store/repository/StoreRepository.java
- src/main/java/org/example/tablenow/domain/store/service/StoreService.java
- src/main/java/org/example/tablenow/global/exception/ErrorCode.java
- src/test/java/org/example/tablenow/domain/store/service/StoreServiceTest.java
close #26
가게 서비스 테스트코드 작성 및 기존 로직 코드 개선 
- `예외`: 존재하지 않는 카테고리, 시작-마감시간 오류, 최대 등록수 초과
- `성공`
- `성공`
- `예외`: 존재하지 않는 가게, 가게 주인이 아닌 경우, 존재하지 않는 카테고리, 시작-마감시간 오류
- `성공`: 요청 데이터가 비어있는 경우
- `예외`: 존재하지 않는 가게, 가게 주인이 아닌 경우
- `성공`
- `예외`: 정렬 옵션 오류, 정렬 기준 오류 
- `성공`: 검색어 제외 조회
- `예외`: 존재하지 않는 가게
- `성공`
- `성공`: 캐시 키 초기화, 존재하지 않는 캐시 내부 데이터 
* 테스트 커버리지
> [test] 가게 API 테스트코드 작성

- src/main/java/org/example/tablenow/domain/event/controller/EventController.java
- src/main/java/org/example/tablenow/domain/event/controller/EventJoinController.java
- src/main/java/org/example/tablenow/domain/event/dto/response/EventJoinResponseDto.java
- src/main/java/org/example/tablenow/domain/event/dto/response/EventResponseDto.java
- src/main/java/org/example/tablenow/domain/event/entity/Event.java
- src/main/java/org/example/tablenow/domain/event/entity/EventJoin.java
- src/main/java/org/example/tablenow/domain/event/enums/EventStatus.java
- src/main/java/org/example/tablenow/domain/event/repository/EventJoinRepository.java
- src/main/java/org/example/tablenow/domain/event/repository/EventRepository.java
- src/main/java/org/example/tablenow/domain/event/service/EventJoinService.java
- src/main/java/org/example/tablenow/domain/event/service/EventOpenScheduler.java
- src/main/java/org/example/tablenow/domain/event/service/EventService.java
- src/main/java/org/example/tablenow/global/config/SchedulingConfig.java
- src/main/java/org/example/tablenow/global/exception/ErrorCode.java
close #35 
기술 고도화 진행 시 Redis ZSet과 MQ로 전환 예정입니다.
> [feat] 이벤트 오픈 스케줄러 구현 및 이벤트 참여 API 구현

- src/main/java/org/example/tablenow/domain/auth/controller/AuthController.java
- src/main/java/org/example/tablenow/domain/user/controller/UserController.java
- src/main/java/org/example/tablenow/domain/user/service/UserService.java
- src/main/java/org/example/tablenow/global/util/CookieUtil.java
> [refactor] 유저 API 리팩토링

- build.gradle
- src/main/java/org/example/tablenow/domain/image/controller/ImageController.java
- src/main/java/org/example/tablenow/domain/image/dto/request/PresignedUrlRequest.java
- src/main/java/org/example/tablenow/domain/image/dto/response/PresignedUrlResponse.java
- src/main/java/org/example/tablenow/domain/image/enums/FileType.java
- src/main/java/org/example/tablenow/domain/image/enums/ImageDomain.java
- src/main/java/org/example/tablenow/domain/image/service/ImageService.java
- src/main/java/org/example/tablenow/global/config/S3Config.java
- src/main/java/org/example/tablenow/global/exception/ErrorCode.java
- src/main/java/org/example/tablenow/global/exception/GlobalExceptionHandler.java
- src/main/java/org/example/tablenow/global/util/RegexConstants.java
- src/main/resources/application.yml
close #61 
- [spring-cloud-aws 버전 결정 참고](https://github.com/awspring/spring-cloud-aws/releases)
- 내용 중: Spring Cloud AWS 3.3.0 brings compatibility with **Spring Boot 3.4**
- 업로드 대상 도메인(user/store)에 따라 S3 디렉토리 경로 분리
- 파일명은 저장 시 UUID + 확장자 형식으로 지정되며, Content-Type은 fileType 기준으로 설정
- 이미지 업로드용 Presigned URL 및 업로드 성공 시 접근 가능한 다운로드 URL 반환
- Presigned URL을 사용하여 이미지 업로드
- 성공
- 실패(URL 시간 만료)
- S3
- 로그인한 유저(id: 12)의 프로필 사진이 업로드 됨
- 다운로드 URL 접근 확인
> [feat] 이미지 업로드 기능 구현

- src/main/java/org/example/tablenow/domain/store/dto/request/StoreCreateRequestDto.java
- src/main/java/org/example/tablenow/domain/store/dto/request/StoreUpdateRequestDto.java
- src/main/java/org/example/tablenow/domain/store/dto/response/StoreDeleteResponseDto.java
- src/main/java/org/example/tablenow/domain/store/entity/Store.java
- src/main/java/org/example/tablenow/domain/store/repository/StoreRepository.java
- src/main/java/org/example/tablenow/domain/store/service/StoreService.java
- src/test/java/org/example/tablenow/domain/store/service/StoreServiceTest.java
close #68
close #73
> #68 테스트파일 리팩토링 
가게 수정, 삭제 시 기존 이미지가 있는 경우 해당 이미지 리소스 찾아서 삭제
> #73 가게 코드리뷰 피드백 반영
`가게 수정`: 가독성 측면을 고려하여 필드 업데이트 메서드 분리
`인기 검색어 조회`: timeKey 검증, 시간별-일자별 구분 분기처리 메서드 추출
* 유효성 검사 관련 메서드명을 valid~로 작성했으나 프로젝트 전체 코드 포맷 일관성을 위해 validate로 변경할 예정입니다.
* 이에 따라 storeService의 validStoreOwnerId를 호출하는 예약(reservation) 의 코드가 일부 변경될 예정입니다. (예상: reservationService 및 테스트코드)
* 가게 이미지 변경 테스트
> [refactor] 가게 코드리뷰 피드백 반영

- src/main/java/org/example/tablenow/domain/category/dto/response/CategoryDeleteResponseDto.java
- src/main/java/org/example/tablenow/domain/category/dto/response/CategoryResponseDto.java
- src/main/java/org/example/tablenow/domain/category/service/CategoryService.java
- src/test/java/org/example/tablenow/domain/category/service/CategoryServiceTest.java
close #81
Entity, Dto의 생성자, 빌더, 접근제한자가 적절하게 적용되었는지 검토
카테고리 중복체크 메서드 추출 -> validExistCategory
- 피드백: ifPresent() → orElse()
> 해당 로직은 동일한 카테고리명의 중복 등록을 방지하기 위해 DB 조회 시 동일한 카테고리명이 있을 경우 예외처리를 위해 작성되어 ifPresent()로 작성하였습니다.
따라서 orElse로 변경하지는 않았으나 등록 API, 수정 API 에서 해당 예외처리가 필요하여 메서드 추출로 중복코드를 삭제하였습니다.
* orElse 수정 시 서버 에러 발생
* 중복 유효성 검사 실패
> [refactor] 카테고리 피드백 반영

- src/test/java/org/example/tablenow/domain/auth/service/AuthServiceTest.java
- src/test/java/org/example/tablenow/domain/auth/service/TokenServiceTest.java
close #99 
- `@ActiveProfiles("test")` 제거
> [test] AuthServiceTest 통합 테스트 개선

- src/main/java/org/example/tablenow/domain/rating/repository/RatingRepository.java
- src/main/java/org/example/tablenow/domain/rating/service/RatingService.java
- src/test/java/org/example/tablenow/domain/rating/service/RatingServiceTest.java
close #104
* 평점 등록
`예외`: 존재하지 않는 가게, 평점을 중복 등록하는 경우, COMPLETED 상태의 예약이 존재하지 않는 경우, 
`성공`
* 평점 수정
`예외`: 존재하지 않는 가게, 존재하지 않는 평점, 평점 등록 수가 0인 경우
`성공`
* 평점 삭제
`예외`: 존재하지 않는 가게, 존재하지 않는 평점
`성공`: 전체 평점 삭제 시 평점 초기화 및 삭제 성공
테스트 진행 중 findByUserIdAndStoreId() 조회 쿼리의 @EntityGraph 설정으로
불필요한 left join 이 발생하고 있는 것을 확인하여 해당 부분 같이 수정하였습니다.
> [test] 평점 API 테스트코드 작성

- src/main/java/org/example/tablenow/domain/category/controller/CategoryController.java
- src/main/java/org/example/tablenow/domain/category/repository/CategoryRepository.java
- src/main/java/org/example/tablenow/domain/category/service/CategoryService.java
- src/main/java/org/example/tablenow/domain/store/controller/StoreController.java
- src/main/java/org/example/tablenow/domain/store/dto/response/StoreCreateResponseDto.java
- src/main/java/org/example/tablenow/domain/store/dto/response/StoreResponseDto.java
- src/main/java/org/example/tablenow/domain/store/dto/response/StoreUpdateResponseDto.java
- src/main/java/org/example/tablenow/domain/store/entity/Store.java
- src/main/java/org/example/tablenow/domain/store/service/StoreService.java
- src/test/java/org/example/tablenow/domain/category/service/CategoryServiceTest.java
- src/test/java/org/example/tablenow/domain/store/service/StoreServiceTest.java
close #108
DTO 객체의 필드는 기본형 타입 대신 Wrapper 클래스 사용 (예: int -> Integer)
생성(Create) API : saveEntity() -> createEntity()
중복 검사 메서드: boolean existsEntity() 으로 중복 검사
코드 수정 후 postman 테스트 확인 및 단위 테스트 검증 완료했습니다.
* 카테고리 등록
* 가게 등록
> [refactor] 가게, 카테고리 API 코드 개선

- src/main/java/org/example/tablenow/domain/reservation/controller/ReservationController.java
- src/main/java/org/example/tablenow/domain/reservation/dto/response/ReservationResponseDto.java
- src/main/java/org/example/tablenow/domain/reservation/entity/Reservation.java
- src/main/java/org/example/tablenow/domain/reservation/repository/ReservationRepository.java
- src/main/java/org/example/tablenow/domain/reservation/service/ReservationService.java
- src/main/java/org/example/tablenow/global/exception/ErrorCode.java
close #128 
- - 기존 `isReservedStatusInUse()`는 "같은 시간대에 예약이 존재하면 무조건 예외"를 발생시켜, 실제로는 **동일 시간대 예약이 1건만 가능**한 구조였습니다.
- 가게 정원이 **하루 단위**이므로, 중복 검증 시 `boolean existsByUserIdAndStoreIdAndReservedAt(Long userId, Long storeId, LocalDateTime reservedAt);` 를 사용하도록 수정해 **동일 유저가 같은 시간에 예약했는지만** 검증했습니다.
- 따라서 유저 단위 중복만 막고, 그날 하루 정원만큼 예약 가능한 구조입니다. 수정해야할 부분이 있으면 말씀해주세요!
- 예약 API는 이벤트 API와 달리 선착순이나 순위가 없고, 몰림 현상이 이벤트보다 적어 ZSet을 사용하지 않았습니다.
> [feat] 예약 생성 API Redisson 락 적용

- src/main/java/org/example/tablenow/domain/auth/service/KakaoAuthService.java
- src/main/java/org/example/tablenow/domain/auth/service/NaverAuthService.java
- src/main/java/org/example/tablenow/domain/auth/service/TokenService.java
- src/main/java/org/example/tablenow/domain/image/service/ImageService.java
- src/main/java/org/example/tablenow/domain/user/service/UserService.java
- src/main/java/org/example/tablenow/global/exception/ErrorCode.java
- src/main/java/org/example/tablenow/global/util/OAuthResponseParser.java
- src/test/java/org/example/tablenow/domain/auth/service/AuthServiceTest.java
- src/test/java/org/example/tablenow/domain/auth/service/KakaoAuthServiceTest.java
- src/test/java/org/example/tablenow/domain/auth/service/NaverAuthServiceTest.java
- src/test/java/org/example/tablenow/domain/auth/service/TokenServiceTest.java
- src/test/java/org/example/tablenow/domain/user/service/UserServiceTest.java
close #140 
close #141 
- 예: `FAILED_TO_PARSE_OAUTH_TOKEN` → `OAUTH_RESPONSE_PARSING_FAILED`
- #130 
- #132 
- #140 
- [리팩토링 사유 정리](https://www.notion.so/teamsparta/1da2dc3ef51480fc9c49d54c853a0d5b?pvs=4)
> [refactor] Redis/OAuth/S3 예외 처리 및 테스트 코드 개선

- src/main/java/org/example/tablenow/domain/reservation/service/ReservationService.java
- src/test/java/org/example/tablenow/domain/reservation/ReservationServiceTest.java
close #145 
- Store 기본 세팅 시 `capacity` 필드 추가 
- `hasVacancy()`는 사용하지 않는 메서드여서 테스트 코드 미작성
> [test] 예약 API(Redisson 락) 테스트 코드 작성 및 기존 테스트 수정

- src/main/java/org/example/tablenow/domain/event/EventJoinExecutor.java
- src/main/java/org/example/tablenow/domain/event/controller/EventController.java
- src/main/java/org/example/tablenow/domain/event/controller/EventJoinController.java
- src/main/java/org/example/tablenow/domain/event/dto/response/EventCloseResponseDto.java
- src/main/java/org/example/tablenow/domain/event/entity/Event.java
- src/main/java/org/example/tablenow/domain/event/service/EventJoinService.java
- src/main/java/org/example/tablenow/domain/event/service/EventService.java
- src/test/java/org/example/tablenow/domain/event/EventJoinServiceTest.java
close #144
- TTL은 Redis 데이터를 자동 삭제하지만, **ZSet이 없어지면 중복 신청 방지/정원 체크가 무력화**되므로 정합성을 보장하지 못합니다. 따라서 **TTL을 삭제** 후 이벤트를 닫는 API를 만들었습니다. **이벤트 닫힘/삭제 상태**가 되면 ZSet에 든 데이터를 삭제합니다.
- 기존 `ZSet.zCard()`로 인원수를 체크하고, 정원이 넘으면 DB count를 추가로 확인하는 구조에서 유저를 ZSet에 추가한 후 `rank()`를 확인하여, 정해진 정원 이내일 때만 insert되도록 수정했습니다.
- [ZSet이 락 밖에서 실행되어 발생하는 오류](https://www.notion.so/teamsparta/ZSet-1dc2dc3ef5148076b19fc16fa9834097?pvs=4)
- [zCard → rank 기반으로 정원 체크 로직 개선](https://www.notion.so/teamsparta/zCard-rank-1dc2dc3ef5148070a3fccfa652b63cd5?pvs=4)
> [refactor] 이벤트 API Redisson AOP 방식으로 구조 개선

- src/main/java/org/example/tablenow/domain/reservation/message/customer/ReminderRegisterConsumer.java
- src/main/java/org/example/tablenow/domain/reservation/message/customer/ReminderSendConsumer.java
- src/main/java/org/example/tablenow/domain/reservation/message/dto/ReminderMessage.java
- src/main/java/org/example/tablenow/domain/reservation/message/producer/ReminderRegisterProducer.java
- src/main/java/org/example/tablenow/domain/reservation/message/producer/ReminderSendProducer.java
- src/main/java/org/example/tablenow/domain/reservation/repository/ReservationRepository.java
- src/main/java/org/example/tablenow/domain/reservation/service/ReminderScheduler.java
- src/main/java/org/example/tablenow/domain/reservation/service/ReservationService.java
- src/main/java/org/example/tablenow/global/rabbitmq/config/RabbitConfig.java
- src/main/java/org/example/tablenow/global/rabbitmq/constant/RabbitConstant.java
close #164 
- [예약 리마인드 알림 Redis ZSET + RabbitMQ 적용](https://www.notion.so/teamsparta/1de2dc3ef51480cdbe57d6cae2b52ce5)(작성전)
- 예약 리마인드 알림은 **등록 시점과 발송 시점이 다르기 때문에**, 
각각의 책임을 분리하여 Producer/Consumer를 두 쌍으로 구성했습니다.
- `ReminderRegisterProducer / Consumer`  
→ 예약 생성 시 알림 등록 메시지를 발행하고,  
→ Consumer가 Redis ZSET에 예약 ID를 등록합니다.
- `ReminderSendProducer / Consumer`  
→ Scheduler가 알림 시간이 도래한 예약을 확인하여 메시지를 발행하고,  
→ Consumer가 알림을 생성합니다.
- 현재는 단일 유저 기준으로 정상 작동을 확인했으나, 
추후 더 많은 알림이 발송되면 지연이 발생할 수도 있어 개선 방향을 생각해보겠습니다.
- MQ 구성은 아래와 같이 분리되어 있습니다.
| 용도 | Exchange | Queue | Routing Key |
|------|----------|--------|-------------|
| 알림 등록 | `reservation.reminder.register.direct` | `reservation.reminder.register.queue` | `reservation.reminder.register.key` |
| 알림 발송 | `reservation.reminder.send.direct` | …
> [feat] RabbitQM 기반 예약 리마인드 알림 기능 구현

- src/test/java/org/example/tablenow/domain/reservation/ReminderSchedulerTest.java
- src/test/java/org/example/tablenow/domain/reservation/ReservationServiceTest.java
close #176 
`@RabbitListener`가 붙은 Consumer 클래스는 Spring 컨테이너에서만 제대로 동작하며, 메시지를 직접 주입하거나 트리거할 수 있는 환경이 필요합니다. 따라서 해당 로직은 **단위 테스트보다 통합 테스트 환경에서 검증하는 것이 적절**합니다. 또한 현재 Consumer 내부의 핵심 로직들은 대부분 별도의 Service를 호출하거나 DTO를 조립하는 작업이므로, 핵심 서비스의 단위 테스트만으로도 기능 보장이 가능하다고 판단했습니다.
`@Scheduled`는 **Spring 컨텍스트 내에서 스케줄링 스레드에 의해 자동 실행**되므로, 단위 테스트 환경에서는 해당 어노테이션이 동작하지 않습니다. 따라서 `pollAndSend()` 메서드를 **직접 호출하는 방식으로 테스트를 수행**했습니다.
- [@Scheduled 메서드는 왜 직접 호출하여 테스트해야 할까?](https://www.notion.so/teamsparta/Scheduled-1df2dc3ef51480279aeec634e59162a3?pvs=4)
> [test] 예약 리마인드 알림 관련 테스트 코드 작성

- src/main/java/org/example/tablenow/domain/store/controller/StoreSearchController.java
- src/main/java/org/example/tablenow/domain/store/dto/response/StoreDocumentResponseDto.java
- src/main/java/org/example/tablenow/domain/store/message/consumer/StoreConsumer.java
- src/main/java/org/example/tablenow/domain/store/message/dto/StoreEventDto.java
- src/main/java/org/example/tablenow/domain/store/message/producer/StoreProducer.java
- src/main/java/org/example/tablenow/domain/store/repository/StoreElasticRepository.java
- src/main/java/org/example/tablenow/domain/store/service/StoreSearchService.java
- src/main/java/org/example/tablenow/domain/store/service/StoreService.java
- src/main/java/org/example/tablenow/domain/store/service/TextAnalyzerService.java
- src/main/java/org/example/tablenow/domain/store/util/StoreConstant.java
- src/main/java/org/example/tablenow/domain/store/util/StoreKeyGenerator.java
- src/main/java/org/example/tablenow/domain/store/util/StoreRedisKey.java
- src/main/java/org/example/tablenow/global/config/CacheConfig.java
- src/main/java/org/example/tablenow/global/dto/PageResponse.java
- src/main/java/org/example/tablenow/global/rabbitmq/config/RabbitConfig.java
- src/main/java/org/example/tablenow/global/rabbitmq/constant/RabbitConstant.java
- src/main/resources/elastic/store-setting.json
- src/test/java/org/example/tablenow/domain/store/service/StoreCreateTest.java
- src/test/java/org/example/tablenow/domain/store/service/StoreSearchServiceTest.java
- src/test/java/org/example/tablenow/domain/store/service/StoreServiceTest.java
close #160 
> 데이터 변경 시점 (DB Create/Update/Delete 발생 시), RabbitMQ를 통해 ElasticSearch 와 Redis 캐시에 변경 사항 반영 → 시스템 데이터 정합성 유지
> ElasticSearch 의 store-setting.json 수정 (미사용 필터, analyzer 삭제)
- `역인덱스`: 불필요한 캐시 삭제 없이 필요한 부분만 삭제
- [데이터 변경 시 Redis + ES 반영](https://www.notion.so/teamsparta/Redis-ES-1de2dc3ef5148013b614d5b7611ac05b)
> [refactor] 가게 데이터 변경 시 Redis + ES 반영

- src/main/java/org/example/tablenow/domain/chat/controller/ChatController.java
- src/main/java/org/example/tablenow/domain/chat/dto/response/ChatAvailabilityResponse.java
- src/main/java/org/example/tablenow/domain/chat/dto/response/ChatMessagePageResponse.java
- src/main/java/org/example/tablenow/domain/chat/dto/response/ChatMessageResponse.java
- src/main/java/org/example/tablenow/domain/chat/dto/response/ChatReadStatusResponse.java
- src/main/java/org/example/tablenow/domain/chat/entity/ChatMessage.java
- src/main/java/org/example/tablenow/domain/chat/repository/ChatMessageRepository.java
- src/main/java/org/example/tablenow/domain/chat/service/ChatMessageService.java
- src/main/java/org/example/tablenow/global/config/WebSocketConfig.java
- src/main/java/org/example/tablenow/global/constant/WebSocketConstants.java
- src/main/java/org/example/tablenow/global/exception/ErrorCode.java
close #168
- @PageableDefault로 page=0, size=20 자동 매핑
- 채팅방(reservationId)에 대해 보낸 사람이 본인이 아닌 경우에 읽지 않은 메시지들을 읽음 처리
- WebSocket 연결 전 상태를 확인하는 용도
- 예약 상태가 RESERVED일 때만 채팅 가능
- reason: available 값에 대한 이유를 상태값(enum)으로 반환
- true일 경우 RESERVED
- false일 경우 CANCELED, COMPLETED
- WebSocket용 컨트롤러 ChatMessageController와 분리된 REST API용 컨트롤러 ChatController 생성
- 메시지 목록 조회 시 Page<T> 응답을 DTO(ChatMessagePageResponse)로 래핑
- Spring 경고 발생 방지 ("Serializing PageImpl instances as-is is not supported...")
- 채팅 가능 여부 확인
- 메시지 목록 조회
- 사용자 기준 읽음 처리
> [feat] 채팅 가능 여부 확인 및 메시지 목록/읽음 처리 API 구현

- src/main/java/org/example/tablenow/domain/event/message/consumer/EventOpenConsumer.java
- src/main/java/org/example/tablenow/domain/event/message/producer/EventOpenProducer.java
- src/main/java/org/example/tablenow/domain/reservation/message/customer/ReminderRegisterConsumer.java
- src/main/java/org/example/tablenow/domain/reservation/message/customer/ReminderSendConsumer.java
- src/main/java/org/example/tablenow/domain/reservation/message/producer/ReminderRegisterProducer.java
- src/main/java/org/example/tablenow/domain/reservation/message/producer/ReminderSendProducer.java
- src/main/java/org/example/tablenow/domain/store/message/consumer/StoreConsumer.java
- src/main/java/org/example/tablenow/domain/store/message/producer/StoreProducer.java
- src/main/java/org/example/tablenow/global/config/RabbitConfig.java
- src/main/java/org/example/tablenow/global/constant/RabbitConstant.java
- src/main/java/org/example/tablenow/global/rabbitmq/vacancy/consumer/VacancyConsumer.java
- src/main/java/org/example/tablenow/global/rabbitmq/vacancy/producer/VacancyProducer.java
close #162
도메인 별 message 패키지를 생성하고 하위로 consumer, dto, producer
RabbitConfig는 기존 config로, RabbitConstant는 constant로 이전
RabbitMQ 패키지 이동으로 아래 소스에 영향이 있습니다.
**event/message**
- `EventOpenConsumer` / `EventOpenProducer`
**reservation/message**
- `ReminderRegisterConsumer` / `ReminderRegisterProducer`
- `ReminderSendConsumer` / `ReminderSendProducer`
store/message
- `StoreConsumer` / `StoreProducer`
---
💡 빈자리(Vacancy) 패키지의 이동 시 #182 와 충돌이 예상되어 도메인 패키지로 이동하지 않았습니다.
- VacancyConsumer / VacancyEventDto / VacancyProducer
→ 패키지 이동은 해당 PR 머지 후 직접 이동 부탁드립니다!
> [refactor] rabbitMQ 패키지 구조 변경

- src/main/java/org/example/tablenow/domain/waitlist/repository/WaitlistRepository.java
- src/main/java/org/example/tablenow/domain/waitlist/service/WaitlistService.java
> fix(waitlist): 날짜별 대기 등록 중복 허용을 위한 중복 체크 조건 수정 (#190)

- src/main/java/org/example/tablenow/domain/event/service/EventJoinExecutor.java
- src/main/java/org/example/tablenow/domain/event/service/EventJoinService.java
- src/main/java/org/example/tablenow/domain/event/service/EventService.java
- src/main/java/org/example/tablenow/domain/reservation/message/customer/ReminderRegisterConsumer.java
- src/main/java/org/example/tablenow/domain/reservation/message/customer/ReminderSendConsumer.java
- src/main/java/org/example/tablenow/domain/reservation/service/ReminderScheduler.java
- src/main/java/org/example/tablenow/domain/reservation/service/ReservationService.java
- src/main/java/org/example/tablenow/global/constant/RedisKeyConstants.java
close #186 
- 다른 도메인의 Redis Key도 해당 파일에서 관리하면 좋을 것 같습니다.
> [refactor] 예약 및 이벤트 Redis Key 상수 클래스로 분리

- src/main/java/org/example/tablenow/domain/reservation/message/customer/ReminderRegisterConsumer.java
- src/main/java/org/example/tablenow/domain/reservation/service/ReminderScheduler.java
- src/main/java/org/example/tablenow/domain/reservation/service/ReservationService.java
- src/main/java/org/example/tablenow/global/constant/TimeConstants.java
close #184 
- postman에서 테스트 시 사용하는 실제 날짜/시간과 Redis에 저장되는 시간이 달라서
지금까지는 테스트 시 `"2025-04-30T10:00:00Z"`와 같이 데이터를 넣고 사용했지만,
이번 작업에서 KST 기준으로 맞춰 정확한 비교가 가능하도록 수정했습니다.
- `Instant.now()`는 UTC 기준이어서, `LocalDateTime.now().atZone(ZoneId.of("Asia/Seoul"))`으로 비교해야 정확했습니다.
> [fix] 예약 변경 및 삭제 시 ZSET 갱신 로직 추가 및 타임존 기준 변경

- Dockerfile.rabbitmq
- docker-compose.yml
- src/main/java/org/example/tablenow/domain/chat/controller/ChatMessageController.java
- src/main/java/org/example/tablenow/domain/chat/dto/response/ChatMessageResponse.java
- src/main/java/org/example/tablenow/domain/chat/message/consumer/ChatConsumer.java
- src/main/java/org/example/tablenow/domain/chat/service/ChatMessageService.java
- src/main/java/org/example/tablenow/domain/notification/enums/NotificationType.java
- src/main/java/org/example/tablenow/global/config/RabbitConfig.java
- src/main/java/org/example/tablenow/global/config/WebSocketConfig.java
- src/main/java/org/example/tablenow/global/constant/RabbitConstant.java
- src/main/java/org/example/tablenow/global/constant/WebSocketConstants.java
- src/main/java/org/example/tablenow/global/exception/ErrorCode.java
- src/main/resources/application-local.yml
- src/main/resources/static/chat.html
close #189
- 이전 구조 (SimpleBroker)에서는 → 서버(Spring)가 직접 클라이언트에게 메시지를 브로드캐스트
- 지금 구조 (StompBrokerRelay)에서는 → 서버(Spring)가 직접 브로드캐스트하지 않고, 받은 메시지를 RabbitMQ로 relay
- WebSocket 연결은 Spring 서버가 담당하고, 메시지 브로커 역할은 RabbitMQ가 수행합니다.
- RabbitMQ STOMP 프로토콜용 TCP 포트(61613)을 추가했습니다.
- [Spring WebSocket 서버] --(STOMP 프레임 over TCP 61613 포트)--> [RabbitMQ]
- 구독 경로를 `/topic/chat/{reservationId}` → `/exchange/amq.topic/chat.{reservationId}`로 변경했습니다.
- [Invalid destination 에러](https://www.notion.so/teamsparta/Spring-WebSocket-RabbitMQ-TCP-Relay-Invalid-destination-1e22dc3ef51480b18d8cc0229f3bdfde)
- 채팅 저장과 알림 저장을 완전히 분리하여, 비동기 처리 구조를 적용했습니다.
- [알림 처리에 대한 고민](https://www.notion.so/teamsparta/RabbitMQ-Relay-1e02dc3ef51480d388aedbbe29690200?pvs=4#1e22dc3ef51480bfb8ccefdeba856883)
- 추후 SimpleBroker vs RabbitMQ Relay …
> [feat] WebSocket + RabbitMQ 기반 채팅 기능 고도화

- build.gradle
- src/main/java/org/example/tablenow/domain/reservation/service/ReminderScheduler.java
- src/main/java/org/example/tablenow/global/config/SchedulingConfig.java
- src/test/java/org/example/tablenow/domain/reservation/ReminderSchedulerTest.java
- src/test/java/org/example/tablenow/domain/reservation/ReservationServiceTest.java
#202 
close #204 
- `@EnableSchedulerLock(defaultLockAtLeastFor = "30s", defaultLockAtMostFor = "1m")`
- [ShedLock 기술적 의사결정](https://www.notion.so/teamsparta/ShedLock-1e32dc3ef51480bf9b44e5afe5fce2e4?pvs=4)
- 스케줄러가 다중 서버 환경에서도 단일 실행되도록 개선했습니다.
- 다른 스케줄러에도 적용 후 이슈 닫도록 하겠습니다.
- PR 닫지 않고 푸쉬해버려서 테스트 코드도 같이 merge됩니다.😓
> [feat] ReminderScheduler에 ShedLock 적용

- src/main/java/org/example/tablenow/domain/event/service/EventOpenScheduler.java
close #202 
- [ShedLock 기술적 의사결정](https://www.notion.so/teamsparta/ShedLock-1e32dc3ef51480bf9b44e5afe5fce2e4?pvs=4)
- 스케줄러가 다중 서버 환경에서도 단일 실행되도록 개선했습니다.
> [feat] EventOpenScheduler에 ShedLock 적용

- src/main/java/org/example/tablenow/domain/event/controller/EventController.java
- src/main/java/org/example/tablenow/domain/event/dto/request/EventRequestDto.java
- src/main/java/org/example/tablenow/domain/event/dto/request/EventUpdateRequestDto.java
- src/main/java/org/example/tablenow/domain/event/dto/response/EventDeleteResponseDto.java
- src/main/java/org/example/tablenow/domain/event/dto/response/EventJoinResponseDto.java
- src/main/java/org/example/tablenow/domain/event/dto/response/EventResponseDto.java
- src/main/java/org/example/tablenow/domain/event/entity/Event.java
- src/main/java/org/example/tablenow/domain/event/entity/EventJoin.java
- src/main/java/org/example/tablenow/domain/event/message/consumer/EventOpenConsumer.java
- src/main/java/org/example/tablenow/domain/event/message/dto/EventOpenMessage.java
- src/main/java/org/example/tablenow/domain/event/message/producer/EventOpenProducer.java
- src/main/java/org/example/tablenow/domain/event/repository/EventJoinRepository.java
- src/main/java/org/example/tablenow/domain/event/repository/EventRepository.java
- src/main/java/org/example/tablenow/domain/event/service/EventJoinExecutor.java
- src/main/java/org/example/tablenow/domain/event/service/EventJoinService.java
- src/main/java/org/example/tablenow/domain/event/service/EventService.java
- src/main/java/org/example/tablenow/global/constant/RedisKeyConstants.java
close #216 
- `Event` :  `getStoreId()`, `getStoreName()`
- `EventJoin` : `getEventId()`, `getStoreId()`, `getStoreName()`, `getEventTime()`
- 그에 따른 응답 DTO 내부 코드 수정
- 누락된 부분이나 오류가 있으면 리뷰 부탁드립니다!
> [refactor] 이벤트 API 리팩토링

- src/main/java/org/example/tablenow/domain/chat/config/RabbitMQProperties.java
- src/main/java/org/example/tablenow/domain/chat/controller/ChatMessageController.java
- src/main/java/org/example/tablenow/domain/chat/dto/request/ChatMessageRequest.java
- src/main/java/org/example/tablenow/domain/chat/entity/ChatMessage.java
- src/main/java/org/example/tablenow/global/config/WebSocketConfig.java
- src/main/java/org/example/tablenow/global/exception/ErrorCode.java
- src/main/resources/static/chat.html
- src/test/java/org/example/tablenow/domain/chat/service/ChatMessageServiceTest.java
close #229
close #231
- [Gatling를 이용한 WebSocket SimpleBroker vs RabbitMQ 성능 비교 테스트](https://www.notion.so/teamsparta/Gatling-WebSocket-SimpleBroker-vs-RabbitMQ-1e32dc3ef5148028a181df680428622d?pvs=4) 진행하면서 수정한 사항입니다.
> [refactor] WebSocket 리팩토링 및 ChatMessageService 단위 테스트 코드 작성

- src/main/java/org/example/tablenow/domain/auth/dto/request/SigninRequest.java
- src/main/java/org/example/tablenow/domain/auth/dto/request/SignupRequest.java
- src/main/java/org/example/tablenow/domain/auth/dto/response/AccessTokenResponse.java
- src/main/java/org/example/tablenow/domain/auth/dto/response/SignupResponse.java
- src/main/java/org/example/tablenow/domain/auth/dto/response/TokenResponse.java
- src/main/java/org/example/tablenow/domain/auth/oAuth/kakao/KakaoUserInfoResponse.java
- src/main/java/org/example/tablenow/domain/auth/oAuth/naver/NaverUserInfoResponse.java
- src/main/java/org/example/tablenow/domain/auth/service/TokenService.java
- src/main/java/org/example/tablenow/global/constant/RedisKeyConstants.java
- src/main/java/org/example/tablenow/global/constant/SecurityConstants.java
- src/main/java/org/example/tablenow/global/filter/JwtAuthenticationFilter.java
- src/test/java/org/example/tablenow/domain/auth/service/AuthServiceTest.java
- src/test/java/org/example/tablenow/domain/auth/service/TokenServiceTest.java
> [refactor] Auth 도메인 Dto 어노테이션 정리 및 Token 관련 Redis 키 상수 이동

- src/main/java/org/example/tablenow/domain/auth/oAuth/kakao/KakaoUserInfoResponse.java
- src/main/java/org/example/tablenow/domain/auth/oAuth/naver/NaverUserInfoResponse.java
- src/test/java/org/example/tablenow/domain/auth/service/AuthServiceTest.java
close #238 
- 테스트에서 동일한 이메일을 사용하는 경우 `이미 가입된 이메일입니다` 예외가 발생하여 테스트 충돌 발생
→ 모든 테스트에서 고정된 이메일을 사용하지 않도록 유니크한 이메일을 생성하여 독립적인 테스트 환경을 보장
- 로그인 테스트 중 `deleteUser()` 호출 후 변경사항이 DB에 반영되지 않는 문제 발생
→ soft delete 후 DB에 반영되지 않아 예외가 발생하지 않던 문제를 save() 호출로 해결
- 실제 애플리케이션에서는 정상 작동하지만, 테스트 코드에서 Kakao/NaverUserInfoResponse의 내부 클래스가 `@NoArgsConstructor(access = PROTECTED)`로 인해 Jackson 역직렬화에 실패함
→  `@NoArgsConstructor`로 변경
> [fix] Auth 도메인 테스트 코드 오류 수정

- src/test/java/org/example/tablenow/domain/event/EventJoinExecutorTest.java
- src/test/java/org/example/tablenow/domain/event/EventJoinServiceTest.java
- src/test/java/org/example/tablenow/domain/event/EventServiceTest.java
close #225 
- 각 테스트 클래스 간 상태 공유를 제거하여 독립적으로 동작하도록 개선했습니다.
> [test] 리팩토링에 따른 이벤트 API 테스트코드 수정

- src/main/java/org/example/tablenow/domain/event/service/EventService.java
- src/main/java/org/example/tablenow/global/exception/ErrorCode.java
close #240
- [dirty checking이 그저께부터 계속 안먹어서](https://www.notion.so/teamsparta/Dirty-Checking-1e42dc3ef51480c980fcd0cb9936c142?pvs=4) 일단 `save()`로 처리해놓았습니다. `save()` 없이도 되는지 확인 한 번만 부탁드립니다!
> [fix] 이벤트 삭제/마감 시 Redis ZSET 제거 누락 수정

- logstash/pipelines/logstash.conf
- src/main/java/org/example/tablenow/domain/rating/service/RatingService.java
- src/main/java/org/example/tablenow/domain/store/dto/response/StoreCreateResponseDto.java
- src/main/java/org/example/tablenow/domain/store/dto/response/StoreDocumentResponseDto.java
- src/main/java/org/example/tablenow/domain/store/dto/response/StoreResponseDto.java
- src/main/java/org/example/tablenow/domain/store/dto/response/StoreSearchResponseDto.java
- src/main/java/org/example/tablenow/domain/store/dto/response/StoreUpdateResponseDto.java
- src/main/java/org/example/tablenow/domain/store/entity/StoreDocument.java
- src/main/java/org/example/tablenow/domain/store/message/consumer/StoreConsumer.java
- src/main/java/org/example/tablenow/domain/store/message/producer/StoreProducer.java
- src/main/java/org/example/tablenow/domain/store/repository/StoreElasticRepository.java
- src/main/java/org/example/tablenow/global/config/RabbitConfig.java
- src/main/java/org/example/tablenow/global/constant/RabbitConstant.java
- src/main/java/org/example/tablenow/global/constant/TimeConstants.java
- src/main/java/org/example/tablenow/global/exception/ErrorCode.java
- src/main/java/org/example/tablenow/global/util/TimeFormatUtil.java
- src/test/java/org/example/tablenow/domain/rating/service/RatingServiceTest.java
- src/test/java/org/example/tablenow/domain/store/message/StoreConsumerTest.java
- src/test/java/org/example/tablenow/domain/store/service/StoreCreateTest.java
- src/test/java/org/example/tablenow/domain/store/utils/StoreJdbcRepository.java
- src/test/java/org/example/tablenow/domain/store/utils/StoreRandomCreator.java
close #248 
`StoreDocument`, `StoreElasticRepository` 변환 코드 추가 / Time UTC -> Asia/Seoul
* Response 클래스에서 시간 패턴 "HH:mm", 
* 날짜 패턴 "yyyy-MM-dd HH:mm:ss" 상수가 필요한 경우 `TimeConstants`의 `TIME_HH_MM`, `TIME_YYYY_MM_DD_HH_MM_SS`로 사용 부탁드립니다.
* AS-IS: Logstash 로 DB 데이터 -> 인덱스 생성 후 조회 시 카테고리명, 시간 데이터 오류
* TO-BE: 수정 후 카테고리명, 시간 데이터 정상 조회
> [fix] 가게 ElasticSearch 인덱스 버그 수정

- src/main/java/org/example/tablenow/domain/notification/message/vacancy/service/VacancyRetryService.java
- src/test/java/org/example/tablenow/domain/waitlist/service/WaitlistServiceTest.java
> [refactor] Redis 락 테스트코드 tryLock 인자(2,2)로 수정하여 오류 해결 

- src/main/java/org/example/tablenow/domain/settlement/batch/schedule/SettlementScheduler.java
- src/main/java/org/example/tablenow/global/constant/RedisKeyConstants.java
- src/test/java/org/example/tablenow/domain/settlement/batch/schedule/SettlementSchedulerTest.java
close #262 
처음에 Scheduler에 적합하다고 알려진 `Scheduler Lock`을 적용하려고 했으나, `settlementRegisterJob`에서 lock을 선점하고 있는 경우에 `Scheduler Lock`의 기본 전략인 skip 때문에 `settlementCompleteJob`이 skip되는 문제가 있었습니다. `settlementCompleteJob`은 하루에 한 번 실행되는 job이기에 skip이 되면 안되기 때문에 Redisson Lock을 적용하여 `SettlementScheduler`를 구현하였습니다.
`settlementRegisterJob`이 lock을 선점하기 위해 `settlementCompleteJob`이 실행되는 시간을 00:00:01로 설정했고, `settlementRegisterJob`이 먼저 수행되면 `isLocked = lock.tryLock(1, 10, TimeUnit.MINUTES)`으로 `settlementCompleteJob`이 최대 1분까지 대기 후, lock을 잡으면 최대 10분까지 lock을 점유하도록 설정했습니다.
> [feat] 정산 스케쥴러 Redisson Lock 적용

- src/main/java/org/example/tablenow/domain/chat/dto/response/ChatMessageResponse.java
- src/main/java/org/example/tablenow/domain/chat/message/consumer/ChatConsumer.java
- src/main/java/org/example/tablenow/domain/chat/message/consumer/ChatDlqReprocessor.java
- src/main/java/org/example/tablenow/domain/chat/message/service/ChatRetryService.java
- src/main/java/org/example/tablenow/global/config/RabbitConfig.java
- src/main/java/org/example/tablenow/global/constant/RabbitConstant.java
close #257 
- 아래 두 PR을 참고했습니다!
- #194 
- #261
- 저도 강제 재처리 테스트를 해봤는데, 3번 재실행 되는 것 확인했습니다. 
- RetryQueue를 따로 적용을 못했는데 이것 때문에 3번 재실행 되는지는 추가로 확인해봐야할 것 같습니다!
- 1번째 재처리 실행
- 4번째 재처리 실행
> [feat] 채팅 알림 DLQ / DLX 적용

- .gitignore
- src/main/java/org/example/tablenow/domain/store/service/StoreSearchService.java
- src/main/java/org/example/tablenow/domain/store/util/StoreKeyGenerator.java
close #260
> 🤔 가게 생성 시 기존 캐시 삭제 이유: 이전 캐시를 불러올 경우 새로 추가된 가게가 포함되어 있지 않아 조회 불가능 
- `전체 캐시 삭제`: 캐시 히트율이 감소 캐시 실효성이 떨어짐 → 인덱스 재조회 : ES 부하 증가
- `조건 키 삭제`: 새로 추가된 가게가 포함될 수 있을 캐시 키를 예측하여 해당 키만 삭제
→ 성능과 데이터 정합성 균형 유지 가능
`AS-IS`: 조건 키 삭제 로직 중 키워드를 검색하지 않은 전체 검색(`*:keyword=`) 캐시가 누락 → 신규 가게를 전체 목록에서 찾을 수 없음
`TO-BE`: 
- 전체 검색(`*:keyword=`) 캐시 + 키워드 ngram 토큰 분해하여 키 탐색 및 삭제
- 카테고리 아이디 기준 조건 삭제 (키워드 조건에 포함되어 굳이 카테고리 기준으로 삭제할 필요가 없음)
> [fix] 가게 데이터 생성 시 인덱스 키 삭제 수정

- src/main/java/org/example/tablenow/domain/user/service/UserService.java
close #256 
- 수정 전 log
- 비밀번호 변경을 시도했을 때 update가 진행되지 않음
- 수정 후 log
- 비밀번호 변경, 프로필 변경, 탈퇴를 순서대로 진행했을 때의 log
- 각 실행에서 update가 정상적으로 수행됨
> [fix] save 추가하여 UserService dirty checking 문제 해결

- src/main/java/org/example/tablenow/domain/event/dto/response/EventJoinResponseDto.java
- src/main/java/org/example/tablenow/domain/event/dto/response/EventResponseDto.java
- src/main/java/org/example/tablenow/domain/event/message/consumer/EventOpenConsumer.java
- src/main/java/org/example/tablenow/domain/event/message/consumer/EventOpenDlqReprocessor.java
- src/main/java/org/example/tablenow/domain/event/message/producer/EventOpenProducer.java
- src/main/java/org/example/tablenow/domain/event/service/EventOpenRetryService.java
- src/main/java/org/example/tablenow/global/config/RabbitConfig.java
- src/main/java/org/example/tablenow/global/constant/RabbitConstant.java
close #270
- **오류 발생 시 30초마다 자동 재전송되며, 최대 3회까지 재시도 후 중단됩니다.**
- Retry 흐름은 DLQ + TTL + 재전송 구조로 안정적으로 구성되었습니다.
- 예약 도메인에도 동일한 재처리 구조를 적용해 수정하겠습니다.
- retryCount 3회 출력, 3회 도달 시 재전송 시도 중단 확인
> [feat] 이벤트 오픈 알림 DLQ / DLX 적용 및 기타 오류 수정

- src/main/java/org/example/tablenow/global/config/WebSocketConfig.java
- src/main/resources/application-local.yml
> [refactor] Amazon MQ로 인한 application.local.yml 과 STOMP 메시징 연결 설정 변경 

- logstash/index-config.json
- src/main/java/org/example/tablenow/domain/store/controller/StoreController.java
- src/main/java/org/example/tablenow/domain/store/enums/StoreSortField.java
- src/main/java/org/example/tablenow/domain/store/repository/StoreElasticRepository.java
- src/main/java/org/example/tablenow/domain/store/service/StoreSearchService.java
- src/main/resources/elastic/store-mapping.json
close #281 
- 검색 정렬 기준: name.keyword 인덱스 기준으로 수정
- 검색 정렬 순서: uppercase 처리
- 가게 설명, 주소 analyzer 추가
- 검색 V1, V2 deprecated
> [fix] 검색 기능 버그 수정
